### ISSUE TITLE
Problem with FileInput

### ISSUE THREAD

**Issue by diegobittencourt** [laminas/laminas-filter#51] opened 2022-03-25 16:08 UTC
My upload file validator is configured as below:

`
[
    'type'     => FileInput::class,
    'name'     => 'image_2',
    'required' => false,
    'validators' => [
        [
            'name'    => 'FileUploadFile',
        ],
        [
            'name'    => 'FileMimeType',                        
            'options' => [                            
                'mimeType'  => [
                    'image/jpeg', 
                    'image/png'
                ]
            ]
        ],
        [
            'name'    => 'FileIsImage'
        ],                          
        [
            'name'    => 'FileImageSize',                        
            'options' => [                            
                'minWidth'  => 128,
                'minHeight' => 128,
                'maxWidth'  => 4096,
                'maxHeight' => 4096
            ]
        ],                    
    ],
    'filters'  => [                    
        [
            'name' => 'FileRenameUpload',
            'options' => [  
                'target'             => './public/img',
                'useUploadName'      => false,
                'useUploadExtension' => true,
                'overwrite'          => true,
                'randomize'          => true,
            ]
        ]
    ],     
],
`
The method `isValid()` is not called from the class `FileInput::class` , but from the class `Input::class` , even though I indicated type as `FileInput::class`.

I checked this situation very carefully and I really believe that this behavior is not appropriate.

I would like to help if doing something wrong.

**Comment by froschdesign** [comment] 2022-04-02 12:21
Duplicate of https://github.com/laminas/laminas-validator/issues/125

**Closed as completed by froschdesign** 2022-04-02 12:21 UTC
Labels: Duplicate
